[package]
name = "host"
version = "0.1.0"
authors = ["TheZoq2 <frans.skarman@gmail.com>"]
edition = "2018"


[dependencies]
spidev = "0.3"
time = "0.1.40"
serde="1.0.82"
serde_derive="1.0.82"
serde_json="1.0.33"

websocket = {version = "0.21.1", default-features = false, features = ["sync"]}
